name: dapr-bot

on:
  issue_comment:
    types: [created]

jobs:
  daprbot:
    name: bot-processor
    runs-on: ubuntu-latest
    steps:
      - name: Comment analyzer
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.DAPR_BOT_TOKEN}}
          script: |
            const script = require('./.github/scripts/dapr_bot.js')
            await script({github, context})
